#! /bin/sh

sxhkd &
~/.fehbg &
xsetroot -cursor_name left_ptr &
picom --config ~/.config/picom.conf &
$HOME/.config/polybar/launch.sh &

bspc monitor DP-2 -d Web Files Discord Spotify
bspc monitor DP-0 -d Code Term

bspc config border_width         0
bspc config window_gap          40

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a discord desktop=Discord state=tiled follow=on
bspc rule -a Code desktop=Code state=tiled follow=on
bspc rule -a Spotify desktop=Spotify follow=on
bspc rule -a firefox desktop=Web follow=on
bspc rule -a kitty desktop=Term follow=on
bspc rule -a nautilus desktop=Files follow=on