#!/bin/sh

sxhkd &
~/.fehbg &
xsetroot -cursor_name left_ptr &
picom --config ~/.config/picom.conf &
xrdb $HOME/.config/X11/xresources &
$HOME/.config/polybar/launch.sh &

focused=$(xrdb ~/.config/X11/xresources -query all | grep foreground | cut -f2)
normal=$(xrdb ~/.config/X11/xresources -query all | grep color8 | cut -f2)

bspc monitor DP-0 -d 1 2 3 4 5

bspc config focused_border_color	"$focused"
bspc config normal_border_color		"$normal"
bspc config border_width		    3
bspc config window_gap 			    6
bspc config focus_follows_pointer	false
bspc config top_padding             40
bspc config split_ratio			    0.52
bspc config borderless_monocle		true
bspc config gapless_monocle		    false
bspc config single_monocle		    true
