#! /bin/sh

sxhkd &
picom --config ~/.config/picom/picom.conf &
~/.fehbg &
xsetroot -cursor_name left_ptr &

bspc monitor DP-2 -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap          15

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Emacs state=tiled

#Set the border colors for your windows for focused, active and inactive ones.
#bspc config normal_border_color "#F808E9"
#bspc config active_border_color "#13CA91"
bspc config focused_border_color "#2365e9"

#Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "#F808E9"

#place the focus on where the mouse is; if you like clicking windows to focus, comment this line
bspc config focus_follows_pointer true

# Polybars
~/.config/polybar/launch.sh &
